generator/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from schedule.views import CalendarByPeriodsView

from generator.periods_extensions import Days
from generator.views import Index, MealPlanView, Index2, GeneratePdf, StatsView, ExtendedOccurrenceView, \
    ExtendedEventView, api_occurrences_corrected
from schedule.urls import urlpatterns as s_urlpatterns

s_urlpatterns.append(
    url(r'^calendar/days/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_week.html'),
        name='days_calendar',
        kwargs={'period': Days}),
)

for url in s_urlpatterns:
    if url.name == 'occurrence':
        url.callback = ExtendedOccurrenceView.as_view()
    if url.name == 'day_calendar':
        url.callback = ExtendedEventView.as_view()
    if url.name == 'api_occurrences':
        url.callback = api_occurrences_corrected

urlpatterns = [
    path('index/', Index2.as_view(), name='index2'),
    path('', Index.as_view(), name='index'),
    re_path(r'^mealplan/(?P<pk>\d+)/$', MealPlanView.as_view(), name='mealplan'),
    path('mealplan/stats/', StatsView.as_view(), name='stats'),
    path('pdf/', GeneratePdf.as_view(),name='pdf'),
]

nutritionplaner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('generator.urls')),
    url(r'^schedule/', include('schedule.urls')),
    url(r'^fullcalendar/', TemplateView.as_view(template_name="fullcalendar.html"), name='fullcalendar'),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

generator/models.py
import pytz
from django.db import models
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from schedule.models import Event, Occurrence, Calendar
from random import randint, shuffle
from generator.utils import sum_nutrient_of_meal, calculate_nutrient_differences, round_half_up, \
    create_occurrence, combine_foods

from .dict import LIMITS_MALE, LIMITS_FEMALE, LIMITS_FEMALE_PREG
import math
from pulp import *
import json

import time
from datetime import datetime, date, timedelta
from django.http import HttpResponse
import copy

utc = pytz.timezone('Europe/Berlin')


def timeit(method):
    def timed(*args, **kw):
        ts = time.time()
        result = method(*args, **kw)
        te = time.time()
        print(str(method), "took time", te - ts)
        return result

    return timed


class JsonResponse(HttpResponse):
    def __init__(self, data):
        super(JsonResponse, self).__init__(
            content=json.dumps(data),
            content_type='text/plain'
        )


final_food_dict = {
    'b': [],
    'l': [],
    'd': [],
    's': []
}


class KeyValue(models.Model):
    '''
    To save some stats

    needed 20 mealplans for:
    min kcal, keep all constraints: DONE
    min kcal, keep only macro: DONE
    min kcal, min sodium (even odd days), keep all constraints:
    min kcal, min sodium (even odd days), keep only macro:
    min kcal, min sodium (typical eals), keep all constraints:
    min kcal, min sodium (typical eals), keep only macro:
    '''
    key = models.CharField('key', max_length=100, null=True, blank=True)
    value = models.CharField('value', max_length=1000000, null=True, blank=True)

    def __str__(self):
        return self.key

    def get_value(self):
        return json.loads(self.value)

    def counting(self):
        # print('count')
        kv_value = self.get_value()
        nutrients_b = {'energy_kcal': 0.0, 'carbs': 0.0, 'fat': 0.0, 'protein': 0.0, 'sugar_total': 0.0, 'fibre': 0.0,
                       'vitamin_a': 0.0, 'vitamin_b1': 0.0, 'vitamin_b2': 0.0, 'vitamin_b3': 0.0,
                       'vitamin_b5': 0.0, 'vitamin_b6': 0.0, 'vitamin_b7': 0.0, 'vitamin_b9': 0.0, 'vitamin_d': 0.0,
                       'vitamin_b12': 0.0,
                       'vitamin_c': 0.0, 'vitamin_e': 0.0, 'vitamin_k': 0.0, 'sodium': 0.0, 'potassium': 0.0,
                       'calcium': 0.0,
                       'magnesium': 0.0, 'phosphorus': 0.0, 'iron': 0.0, 'zinc': 0.0, 'copper': 0.0, 'manganese': 0.0,
                       'fluoride': 0.0, 'iodide': 0.0}
        nutrients_list = {'energy_kcal': [], 'carbs': [], 'fat': [], 'protein': [], 'sugar_total': [], 'fibre': [],
                          'vitamin_a': [], 'vitamin_b1': [], 'vitamin_b2': [], 'vitamin_b3': [],
                          'vitamin_b5': [], 'vitamin_b6': [], 'vitamin_b7': [], 'vitamin_b9': [], 'vitamin_d': [],
                          'vitamin_b12': [],
                          'vitamin_c': [], 'vitamin_e': [], 'vitamin_k': [], 'sodium': [], 'potassium': [],
                          'calcium': [],
                          'magnesium': [], 'phosphorus': [], 'iron': [], 'zinc': [], 'copper': [], 'manganese': [],
                          'fluoride': [], 'iodide': []}
        nutrients_l = nutrients_b.copy()
        nutrients_d = nutrients_b.copy()
        nutrients_s = nutrients_b.copy()
        nutrients_b2 = nutrients_b.copy()
        nutrients_l2 = nutrients_b.copy()
        nutrients_d2 = nutrients_b.copy()
        nutrients_s2 = nutrients_b.copy()
        nutrients_listl = copy.deepcopy(nutrients_list)
        nutrients_listd = copy.deepcopy(nutrients_list)
        nutrients_lists = copy.deepcopy(nutrients_list)
        counts = {'breakfast': nutrients_b,
                  'lunch': nutrients_l,
                  'dinner': nutrients_d,
                  'snack': nutrients_s,
                  }
        counts2 = {'breakfast': nutrients_b2,
                   'lunch': nutrients_l2,
                   'dinner': nutrients_d2,
                   'snack': nutrients_s2,
                   }
        counts3 = {'breakfast': nutrients_list,
                   'lunch': nutrients_listl,
                   'dinner': nutrients_listd,
                   'snack': nutrients_lists,
                   }
        for diffs_dict in kv_value:
            # print(diffs_dict)
            if 'breakfast' in diffs_dict['name']:
                for key in diffs_dict:
                    if key in nutrients_b.keys():
                        counts['breakfast'][key] += 1 if diffs_dict[key] != 0 else 0
                        counts2['breakfast'][key] = diffs_dict[key]
                        counts3['breakfast'][key].append(diffs_dict[key])
            if 'lunch' in diffs_dict['name']:
                for key in diffs_dict:
                    if key in nutrients_l.keys():
                        counts['lunch'][key] += 1 if diffs_dict[key] != 0 else 0
                        counts2['lunch'][key] = diffs_dict[key]
                        counts3['lunch'][key].append(diffs_dict[key])
            if 'dinner' in diffs_dict['name']:
                for key in diffs_dict:
                    if key in nutrients_d.keys():
                        counts['dinner'][key] += 1 if diffs_dict[key] != 0 else 0
                        counts2['dinner'][key] = diffs_dict[key]
                        counts3['dinner'][key].append(diffs_dict[key])
            if 'first snack' in diffs_dict['name']:
                for key in diffs_dict:
                    if key in nutrients_s.keys():
                        counts['snack'][key] += 1 if diffs_dict[key] != 0 else 0
                        counts2['snack'][key] = diffs_dict[key]
                        counts3['snack'][key].append(diffs_dict[key])
        '''for diffs_dict in kv_value:
            for key in diffs_dict:
                if diffs_dict['name'] in counts3.keys():
                    counts3[diffs_dict['name']][key] = diffs_dict[key]
                else:
                    counts3[diffs_dict['name']] = nutrients_b.copy()
                    counts3[diffs_dict['name']][key] = diffs_dict[key]'''
        # print(counts3)
        kv = KeyValue(key='stats_counted_now_6')
        kv.value = json.dumps(counts)
        kv.save()
        kv = KeyValue(key='stats_values_last_meal_now_6')
        kv.value = json.dumps(counts2)
        kv.save()
        kv = KeyValue(key='stats_values_list_now_6')
        kv.value = json.dumps(counts3)
        kv.save()


class Person(models.Model):
    name = models.CharField('Name', max_length=20, blank=True, null=True)
    gender = models.CharField('Geschlecht', max_length=7, default='f', choices=(('m', 'Mann'), ('f', 'Frau')))
    age = models.PositiveSmallIntegerField('Alter')
    weight = models.FloatField('Gewicht (kg)')
    height = models.IntegerField('Größe (cm)')
    nutrition_habit = models.CharField('Essweise', max_length=11, default='o',
                                       choices=(('o', 'Alles'), ('veggie', 'Vegetarisch'), ('v', 'Vegan')))
    allergies = models.CharField('Allergien', max_length=11, default='k',
                                 choices=(('k', 'Keine'), ('l', 'Laktose'), ('n', 'Nüsse'), ('f', 'Fruktose'),
                                          ('ln', 'Laktose, Nüsse'), ('lf', 'Laktose, Fruktose'),
                                          ('nf', 'Nüsse, Fruktose'), ('lnf', 'Laktose, Nüsse, Fruktose')))
    activity = models.CharField('Aktivitäslevel', max_length=11, null=True, blank=True, default=2,
                                choices=(
                                    ('1', u'Sitzend oder liegend (1)'),
                                    ('2', u'Sitzend und leichte Freizeitaktivitäten (2)'),
                                    ('3', u'Sitzend, laufend und leichte Freizeitaktivitäten (3)'),
                                    ('4', u'Überwiegend stehened und laufend (4)'),
                                    ('5', u'Körperlich anstrengende Arbeit und viele Freizeitaktivitäten (5)')),
                                help_text=u'Hier gilt folgende Zuordnung: 1: Bettlägerige |\n2: Büroangestellte |\n3: Studenten |\n4: Kellner |\n5: Bauarbeiter')
    sports = models.BooleanField(u'Sport oder anstrengende Freizeitaktivitäten', default=False,
                                 help_text=u'Falls man min. 4-5x die Woche 30-60min Sport macht')

    goal = models.CharField('Ziel', max_length=11, default='k',
                            choices=(('l', 'Gewicht verlieren'), ('g', 'Gewicht zunehmen'), ('k', 'Gewicht halten')))
    pregnant = models.CharField('Schwanger', max_length=11, default='n',null=True, blank=True,
                                choices=(('n', 'Nein'), ('y', 'Ja')))

    plan = models.CharField('plan', max_length=10000, null=True, blank=True)
    preferences = models.CharField('Vorlieben', max_length=10000, null=True, blank=True,
                                   help_text=u'Kommagetrennte Liste von expliziten Lebensmitteln angeben (Gemüse, Fisch, Wurst, Obst etc. sind also keine expliziten Lebensmittel - Karotte, Salami hingegen schon). Erhöht die Chance, '
                                             u'dass diese Lebensmittel öfter zur Verfügung stehen.')
    dislikes = models.CharField('Abneigungen', max_length=10000, null=True, blank=True,
                                help_text=u'Kommagetrennte Liste von expliziten Lebensmitteln angeben (Gemüse, Fisch, Wurst, Obst etc. sind also keine expliziten Lebensmittel - Karotte, Salami hingegen schon). Ignoriert diese Lebensmittel '
                                          u'komplett bei der Planerstellung.')

    calendar = models.ForeignKey(Calendar, null=True, blank=True, on_delete=models.CASCADE, verbose_name="calendar",
                                 related_name='personcalendar')

    generating_time = models.FloatField(u'Benötigte Zeit zum Generieren (min)', null=True, blank=True, default=0.0)

generator/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import DateInput, NumberInput

from generator.models import Person, MealSet


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        exclude = ['plan']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Namen/Pseudonym (nur Buchstaben & Zahlen)'}),
            'height': forms.NumberInput(
                attrs={'placeholder': u'Größe in cm'}),
            'weight': forms.NumberInput(
                attrs={'placeholder': u'Gewicht in kg'}),
            'preferences': forms.TextInput(
                attrs={'placeholder': u'Kommagetrennte Liste von expliziten Lebensmitteln'}),
            'dislikes': forms.TextInput(
                attrs={'placeholder': u'Kommagetrennte Liste von expliziten Lebensmitteln'}),
        }

    def clean(self):
        data = super().clean()
        if 'name' in data and data['name']:
            if not data['name'].isalnum():
                self._errors['name'] = self.error_class([u'Nur Buchstaben und Zahlen sind erlaubt'])
        if 'age' in data and data['age']:
            if data['age'] < 19:
                self._errors['age'] = self.error_class([u'Ein Mindestalter von 19 Jahren ist erforderlich'])
        if 'height' in data and data['height']:
            if not isinstance(data['height'], int):
                self._errors['height'] = self.error_class([u'Gib die Größe in cm an'])
        if 'preferences' in data and data['preferences']:
            words = data['preferences'].split(',')
            words2 = []
            for word in words:
                word = word.strip()
                word = word.casefold()
                word = word.replace('ü', 'ue')
                word = word.replace('ä', 'ae')
                word = word.replace('ö', 'oe')
                words2.append(word)
                word = word[0].upper() + word[1:]
                words2.append(word)
            regex = '|'.join(words2)
            data['preferences'] = regex
        if 'dislikes' in data and data['dislikes']:
            words = data['dislikes'].split(',')
            words2 = []
            for word in words:
                word = word.strip()
                word = word.casefold()
                word = word.replace('ü', 'ue')
                word = word.replace('ä', 'ae')
                word = word.replace('ö', 'oe')
                words2.append(word)
                word = word[0].upper() + word[1:]
                words2.append(word)
            regex = '|'.join(words2)
            data['dislikes'] = regex
        return data


class GeneratorForm(forms.Form):
    hidden_start = forms.DateField(label='Von: ', widget=DateInput(attrs={'type': 'date'}))
    hidden_end = forms.DateField(label='Bis: ', widget=DateInput(attrs={'type': 'date'}))
    person_id = forms.IntegerField(widget=NumberInput(attrs={'type': 'hidden'}))

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['hidden_start'] and cleaned_data['hidden_end']:
            person = Person.objects.get(id=cleaned_data['person_id'])
            meals = MealSet.objects.filter(person=person, date__gte=cleaned_data['hidden_start'], date__lte=cleaned_data['hidden_end'])
            if meals:
                raise forms.ValidationError(u'Für diese Auswahl gibt es bereits Essenspläne.')
        if not cleaned_data['hidden_start'] or not cleaned_data['hidden_end']:
            raise forms.ValidationError(u'Bitte vervollständige deine Auswahl')
        return cleaned_data

generator/templates/generator/index.html
<!DOCTYPE html>
{% load i18n static staticfiles %}
<html lang="de-de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon Stuff-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "generator/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "generator/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "generator/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "generator/favicon/site.webmanifest" %}">
    <link rel="mask-icon" href="{% static "generator/favicon/safari-pinned-tab.svg" %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#c4a9b0">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "schedule.css" %}" type="text/css" media="screen">

    <!-- jQuery style for Tooltips -->
    <link href="{% static "js/jquery-ui-themes-1.12.1/themes/base/jquery-ui.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "js/jquery-ui-themes-1.12.1/themes/base/theme.css" %}" rel="stylesheet" type="text/css"/>
    <!-- style for fullcalendar -->
    <link rel="stylesheet" href="{% static "js/jquery.qtip.css" %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static "fullcalendar/core/main.css" %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static "fullcalendar/daygrid/main.css" %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static "fullcalendar/timegrid/main.css" %}" type="text/css" media="screen">

    <link rel="stylesheet" href="{% static "generator/styles.css" %}" type="text/css" media="screen">

    {% block extra_head %}
    {% endblock %}
    <title>Ernährungsplan</title>
</head>
<body>

{% block main_content %}
    <header><h1>Erstelle deinen monatlichen Ernährungsplan*!</h1></header>

    <form id="personsform" action="{% url 'index' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="mycol-1">
            <div class="fieldWrapper{% if form.name.errors %} error{% endif %}">
                {{ form.name.errors }}
                <label for="{{ form.name.id_for_label }}">Name:</label>
                {{ form.name }}
            </div>
            <div class="fieldWrapper{% if form.gender.errors %} error{% endif %}">
                {{ form.gender.errors }}
                <label for="{{ form.gender.id_for_label }}">Geschlecht:</label>
                {{ form.gender }}
            </div>
            <div class="fieldWrapper{% if form.age.errors %} error{% endif %}">
                {{ form.age.errors }}
                <label for="{{ form.age.id_for_label }}">Alter:</label>
                {{ form.age }}
            </div>
            <div class="fieldWrapper{% if form.weight.errors %} error{% endif %}">
                {{ form.weight.errors }}
                <label for="{{ form.weight.id_for_label }}">Gewicht (kg):</label>
                {{ form.weight }}
            </div>
            <div class="fieldWrapper{% if form.height.errors %} error{% endif %}">
                {{ form.height.errors }}
                <label for="{{ form.height.id_for_label }}">Größe (cm):</label>
                {{ form.height }}
            </div>
            <div class="fieldWrapper{% if form.pregnant.errors %} error{% endif %}">
                {{ form.pregnant.errors }}
                <label for="{{ form.pregnant.id_for_label }}">Schwanger:</label>
                {{ form.pregnant }}
            </div>
            <div class="fieldWrapper{% if form.goal.errors %} error{% endif %}">
                {{ form.goal.errors }}
                <label for="{{ form.goal.id_for_label }}">Ziel:</label>
                {{ form.goal }}
            </div>
        </div>
        <div class="mycol-2">
            <div class="fieldWrapper{% if form.activity.errors %} error{% endif %}">
                {{ form.activity.errors }}
                <label for="{{ form.activity.id_for_label }}">Aktivitätslevel:
                    <i class="fa fa-info-circle" title="{{ form.activity.help_text }}"></i>
                </label>
                {{ form.activity }}
            </div>
            <div class="fieldWrapper{% if form.sports.errors %} error{% endif %}">
                {{ form.sports.errors }}
                <label for="{{ form.sports.id_for_label }}">Sport oder anstrengende Freizeitaktivitäten:
                    <i class="fa fa-info-circle" title="{{ form.sports.help_text }}"></i>
                </label>
                {{ form.sports }}
            </div>
            <div class="fieldWrapper{% if form.nutrition_habit.errors %} error{% endif %}">
                {{ form.nutrition_habit.errors }}
                <label for="{{ form.nutrition_habit.id_for_label }}">Essweise:</label>
                {{ form.nutrition_habit }}
            </div>
            <div class="fieldWrapper{% if form.allergies.errors %} error{% endif %}">
                {{ form.allergies.errors }}
                <label for="{{ form.allergies.id_for_label }}">Allergien:</label>
                {{ form.allergies }}
            </div>
            <div class="fieldWrapper{% if form.preferences.errors %} error{% endif %}">
                {{ form.preferences.errors }}
                <label for="{{ form.preferences.id_for_label }}">Vorlieben:
                    <i class="fa fa-info-circle" title="{{ form.preferences.help_text }}"></i>
                </label>
                {{ form.preferences }}
            </div>
            <div class="fieldWrapper{% if form.dislikes.errors %} error{% endif %}">
                {{ fform.dislikes.errors }}
                <label for="{{ form.dislikes.id_for_label }}">Abneigungen:
                    <i class="fa fa-info-circle" title="{{ form.dislikes.help_text }}"></i>
                </label>
                {{ form.dislikes }}
            </div>
        </div>

        <input type="submit" value="Abschicken"/>
    </form>
    <p class="planinfo">
        *Dieser Ernährungsplan bezieht nur feste Lebensmittel mit ein. Das bedeutet, Getränke können beliebig (natürlich in Maßen) verzehrt werden und die Gerichte können nach Belieben gewürzt und verfeinert werden. Dieser Plan soll lediglich als Empfehlung dienen, sodass die Lebensmittel zwischen den einzelnen Mahlzeiten vertauscht werden dürfen. Ebenso zielt der Plan stets nur die Untergrenzen der Makronährstoffe an, sodass ein Puffer an aufzunehmenden Kalorien besteht.<br>
        Beim Zubereiten verlieren viele Lebensmittel Nährstoffe. Desweiteren nimmt der Körper nur so viel an Nährstoffen auf wie er auch verarbeiten kann. Überschüssiges wird ausgeschieden.
    </p>
    <div id="container" style="width:1500px;margin: 0 auto"></div>

    <div id="calendar">

    </div>
{% endblock main_content %}

<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/jquery-ui.js" %}"></script>
<script src="{% static "js/moment.js" %}"></script>
<script src="{% static "js/jquery.qtip.js" %}"></script>


<!--script src="{% static "bootstrap-3.3.5-dist/js/bootstrap.min.js" %}"></script-->
<script src="{% static "schedule.js" %}"></script>

<script src="{% static "fullcalendar/core/main.js" %}"></script>
<script src="{% static "fullcalendar/core/de.js" %}"></script>
<script src="{% static "fullcalendar/interaction/main.js" %}"></script>
<script src="{% static "fullcalendar/daygrid/main.js" %}"></script>
<script src="{% static "fullcalendar/timegrid/main.js" %}"></script>

<script type="module" src="{% static "fullcalendar/popper/popper.js" %}"></script>
<script type="module" src="{% static "fullcalendar/tooltip/tooltip.js" %}"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="{% static "generator/generator.js" %}"></script>
<script type="text/javascript">
    //events: '/mealplan/'+id+'?ask'
    $(document).ready(function () {
        //document.addEventListener('DOMContentLoaded', function () {
        id = '{{ person.id }}';

        $('.fa-info-circle').tooltip({
            classes: {
                "ui-tooltip": " "
            }
        });
        $('#id_gender').change(function () {
            if($('#id_gender').val() !== 'f'){
                $('#id_pregnant').attr('disabled','disabled');
            }
            else{
                $('#id_pregnant').removeAttr('disabled');
            }
        });

        var stats_area = $('#container');
        var formatter = function () {
            if (this.y > 0)
                return this.y + ' ' + this.series.name;
            if (this.y < 0)
                return this.y + ' ' + this.series.name;
        };
        stats_area.html('');
        /*$.ajax(
            {
                url: "stats?kv_key=stats_values_list",
                type: "GET",
                dataType: 'json',
                success: function (result) {
                    console.log(result)
                    result.forEach(function (element, index, array) {
                        element.plotOptions.series.dataLabels.formatter = formatter;
                        console.log(element.plotOptions)
                        Highcharts.chart('container', element)
                    });
                },
                error: function (e) {
                    console.log(e);
                }
            });*/
        $('.fa-times').click(function () {
            $(this).parent('.popupWrapper').hide();
        });

    });
</script>
{% block scripts %}
{% endblock scripts %}
</body>
</html>

generator/templates/generator/ingredients_detail.html
<table {% if fcdescription %}class="fc-description"{% else %}class="ingredients_table"{% endif %}>
    <!--thead>
    <tr>
        <td>Zutaten</td>
        <td class="portion_size">Portionsgröße</td>
    </tr>
    </thead-->
    <tbody>
    {% for ingred in ingredients %}
        <tr {% if fcdescription %}class="dotted_line{% if forloop.last %} last{% endif %}"{% endif %}>
            <td>{{ ingred.0 }}</td>
            <td class="portion_size">{{ ingred.1|floatformat:"-2" }} g</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

generator/templates/generator/meal_detail.html
{% load tags %}
<span class="close" style="max-width:{{ container_max_width }}px"><i class="fa fa-times"></i></span>

<div class="mealset_container" style="width:{{ container_width }}%">
    <h1>{{ occurrence.start|date:'D., d.b' }}</h1>
    {% if meal %}
        <h4>
            {{ meal.mealtype.name }}
            <sup>{% if meal.note %}<i class="fa fa-exclamation-triangle" title="{{ meal.note }}"></i>{% endif %}{{ meal.mealtype.starttime|date:'H:i' }} - {{ meal.mealtype.endtime|date:'H:i' }} Uhr</sup>
        </h4>
        {% get_ingredients_infos meal %}
        <div class="nutrients_container" style="max-width:{{ container_max_width }}px">
            <span class="heading">Nährwerte:</span>
            {% get_nutrients_infos meal=meal %}
        </div>
    {% else %}
        <p>
            <span>Für diesen Tag wurde noch kein Gericht erstellt.</span>
        </p>
    {% endif %}
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(' .fa-exclamation-triangle').tooltip({
            classes: {
                "ui-tooltip": "dark"
            }
        });
    })
</script>

generator/templates/generator/nutrients_detail.html
<span class="heading">Makronährstoffe:</span>
{% for nutri in nutrients %}
    {% if forloop.counter == 11 %}
        <span class="heading_v">Vitamine:<i class="fa fa-chevron-down"></i>
        </span>
        <div class="inner_v">
    {% elif forloop.counter == 24 %}
        </div>
        <span class="heading_m">Mineralien & Spurenelemente:<i class="fa fa-chevron-down"></i>
        </span>
        <div class="inner_m">
    {% endif %}
    {{ nutri|safe }}
{% endfor %}
</div>